src/objects/Build__c.object
<CustomObject>
    <fields>
        <fullName>Check_Only__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This will only validate the code in the target organization.</inlineHelpText>
        <label>Check Only/Validate Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connection</label>
        <referenceTo>Connection__c</referenceTo>
        <relationshipLabel>Builds</relationshipLabel>
        <relationshipName>Builds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TestClasses__c</fullName>
        <label>TestClasses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test_Options__c</fullName>
        <label>Test Options</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Run Local Tests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Run All Tests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Run Specified Tests</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Build</label>
    <nameField>
        <displayFormat>BUILD-{0000}</displayFormat>
        <label>Build Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Build_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Build</label>
        <referenceTo>Build__c</referenceTo>
        <relationshipLabel>Build Change Requests</relationshipLabel>
        <relationshipName>Build_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>Build Change Requests</relationshipLabel>
        <relationshipName>Build_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Build Change Request</label>
    <nameField>
        <displayFormat>BCR-{0}</displayFormat>
        <label>Build Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>CR_ID__c</fullName>
        <label>CR-ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Change Request</relationshipLabel>
        <relationshipName>Change_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <label>Change Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Source_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Connections (Target Org)</relationshipLabel>
        <relationshipName>Connections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Salesforce_Org__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sandbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Saleforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BuildPageController.cls
public with sharing class BuildPageController {
	 
	public Build__c build {get;set;} //adding comment form work pc 
	public Boolean isEdit {get;set;}//This is master branch
	public List<Build_Change_Request__c> buildChangeRequests {get;set;}
    public BuildPageController(ApexPages.StandardController std){
		if(std.getId()!=null){
		   build = [Select Id,Check_Only__c,Connection__c,Description__c,Test_Options__c,TestClasses__c,Name From Build__c WHERE ID=:std.getId()];	
		   populateBuildChangeRequests();
		   String readOnlyMode = ApexPages.currentPage().getParameters().get('readOnlyMode');	
		   if(readOnlyMode != null && readOnlyMode == 'true'){
		   	   isEdit = false;
		   }else{
			   isEdit = true;	
		   }
		} 
	} 
	
	private void populateBuildChangeRequests(){
		buildChangeRequests = [Select Id, Change_Request__r.Name,Change_Request__r.CR_ID__c From Build_Change_Request__c WHERE Build__c =:build.Id];
	}
	
	public PageReference save(){
		upsert build;
		isEdit = false; 
		return null;
	}
	
	public PageReference edit(){
		isEdit = true;
		return null;
	}
	
	/**
	* This method will navigate the page in view only mode since this method got called from 
	* the page which has been configured to be opened in view mode when clicked on any build object record.
	*/
	public PageReference viewModeActionMethod(){
		isEdit = false;
		PageReference pg =  new PageReference('/apex/BuildPage?id='+build.Id+'&readOnlyMode=true');
		pg.setRedirect(true);
		return pg;  
	}
	
	
	@RemoteAction
	public static String getDeploymentStatus(){
		HttpRequest req = new HttpRequest();
	    req.setEndpoint('https://kmforce4.herokuapp.com/DeployCode');
	    req.setMethod('GET');     
	    Http http = new Http();
	    HTTPResponse res = http.send(req);
	    System.debug(res.getBody());	
	    return res.getBody(); 
	}
	 
	public PageReference showMessage(){
		String message = ApexPages.currentPage().getParameters().get('message');
		String isError = ApexPages.currentPage().getParameters().get('isError');
		if(isError == 'true'){
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, message);
	        ApexPages.addMessage(msg);
		}else{
			ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Confirm, message);
	        ApexPages.addMessage(msg);
		}		 
		return null;
	}
	
	
	@RemoteAction
	public static String startDeployment(String buildId){
		Build__c build = [SELECT ID, (Select Id, Change_Request__c From Build_Change_Requests__r ), TestClasses__c, Test_Options__c,Connection__c FROM Build__c WHERE Id=:buildId][0];
		Set<Id> changeSetRequestIds = new Set<Id>();
		for(Build_Change_Request__c bcr : build.Build_Change_Requests__r){
			changeSetRequestIds.add(bcr.Change_Request__c);
		}
		return ChangeRequestService.deployChangeRequests([select id from Change_Request__c WHERE Id in : changeSetRequestIds],[
			Select Id, 
				Source_org__r.Username__c,
				Source_org__r.Password__c,
				Source_org__r.Type__c,
				Target_org__r.Username__c,
				Target_org__r.Password__c,
				Target_org__r.Type__c
			From Connection__c WHERE Id=:build.Connection__c
		][0],false,build.TestClasses__c,build.Test_Options__c);	
		
	}  
	
	@RemoteAction
	public static Object startValidation(String buildId){
		Build__c build = [SELECT ID, (Select Id, Change_Request__c From Build_Change_Requests__r ), TestClasses__c, Test_Options__c, Connection__c FROM Build__c WHERE Id=:buildId][0];
		Set<Id> changeSetRequestIds = new Set<Id>();
		for(Build_Change_Request__c bcr : build.Build_Change_Requests__r){
			changeSetRequestIds.add(bcr.Change_Request__c);
		}
		return ChangeRequestService.deployChangeRequests([select id from Change_Request__c WHERE Id in : changeSetRequestIds],[
			Select Id, 
				Source_org__r.Username__c,
				Source_org__r.Password__c,
				Source_org__r.Type__c,
				Target_org__r.Username__c,
				Target_org__r.Password__c,
				Target_org__r.Type__c
			From Connection__c WHERE Id=:build.Connection__c
		][0],true,build.TestClasses__c,build.Test_Options__c);	
	}
	
}