src/objects/Change_Request__c.object
<CustomObject>
    <label>Change Request</label>
    <nameField>
        <label>Change Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>Component</relationshipLabel>
        <relationshipName>Component</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Component</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Copmonents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Source_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Connections</relationshipLabel>
        <relationshipName>Connections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Connections (Target Org)</relationshipLabel>
        <relationshipName>Connections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Salesforce_Org__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sandbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Saleforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PackageXMLBuilder.cls
public with sharing class PackageXMLBuilder {
	
	public class Element{
		public String elementName {get;set;}
		public String apiVersion  {get;set;}		
		public Element(String elementName,String apiVersion){
			this.elementName = elementName;
			this.apiVersion = apiVersion;
		}
		public Element(String elementName){
			this.elementName = elementName;
		}
	}
	
	public static void test(){
		new PackageXMLBuilder().getXML([select id from Change_Request__c WHERE Id='a012800000JbNUX'],[
			Select Id, 
				Source_org__r.Username__c,
				Source_org__r.Password__c,
				Source_org__r.Type__c,
				Target_org__r.Username__c,
				Target_org__r.Password__c,
				Target_org__r.Type__c
			From Connection__c WHERE Id='a042800000BSAg4'
		][0]);
	} 
	
	public String getXML(List<Change_Request__c> changeRequests, Connection__c connection){
		Map<String,Set<Element>> metadataItems = new Map<String,Set<Element>>();		
		List<String> commonProfiles = MetadataSyncService.getCommonProfiles(connection);  
		String xmlHeader = '<?xml version="1.0" encoding="UTF-8"?>';
		xmlHeader +='<Package xmlns="http://soap.sforce.com/2006/04/metadata">';
		String xmlFooter = '</Package>';
		
		for(Component__c component : [SELECT Id,Component_Name__c,
													Type__c
									  From Component__c WHERE Change_Request__c in :changeRequests]){	
			if(metadataItems.get(component.Type__c)==null){
				metadataItems.put(component.Type__c,new Set<Element>());
			}																	
			metadataItems.get(component.Type__c).add(new Element(component.Component_Name__c));								
		}
		metadataItems.put('Profile',new Set<Element>());  		
		for(String profile : commonProfiles){
			metadataItems.get('Profile').add(new Element(profile));
		} 
		System.debug('MetadataItems-->'+JSON.serializePretty(metadataItems));
		System.debug('PackageXML-->'+(xmlHeader + getXMLBody(metadataItems) + xmlFooter)); 		
		return (xmlHeader + getXMLBody(metadataItems) + xmlFooter).escapeXML();  		
		
	}
	
	public String getXMLBody(Map<String,Set<Element>> metadataItems){
		String body ='';
		for(String metadata : metadataItems.keySet()){
			body += '<types>';
				for(Element elem : metadataItems.get(metadata) ){
					body += '<members>'+elem.elementName+'</members>';
				}
				body +='<name>'+metadata+'</name>';
			body +='</types>';
		}
		body +='<version>35.0</version>';
		return body;
	}
	
	
	
	
	
	
	
	
    
}